version: '3.8'

services:
  debug:
    build:
      context: ${PWD}
      dockerfile: Dockerfile-bids
    tty: true
    stdin_open: true
    volumes:
      - ${PWD}:/workspace
      - ${PWD}/../nnUNet:/nnUNet
      - ${PWD}/../nnUNet_forked:/nnUNet_forked
    environment:
      - CHECK_CRC=False
  
  bids:
    build:
      context: ${PWD}
      dockerfile: Dockerfile-bids
    tty: true
    stdin_open: true
    volumes:
      - ${PWD}:/workspace
      - ${PWD}/../nnUNet:/nnUNet
      - ${PWD}/../nnUNet_forked:/nnUNet_forked
    environment:
      - CHECK_CRC=False
  
  union:
    container_name: Union-Operation
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ${PWD}:/workspace
      - ${PWD}/../nnUNet:/nnUNet
      - ${PWD}/../nnUNet_forked:/nnUNet_forked
    environment:
      # - A_PATH=/nnUNet/outputs/output_Task510_3d_fullres_ATLAS_ATLAS_1000EP_8:2val
      # - B_PATH=union/2d0-2d1-2d2_1000EP_8vs2val
      # - A_PATH=/nnUNet/outputs/output_Task501_2d_ATLAS_ATLAS_1000EP_8:2val
      # - B_PATH=/nnUNet/outputs/output_Task502_2d_ATLAS_ATLAS_1000EP_8:2val
      # - B_PATH=/nnUNet/ensemble/3d-2d0_1000EP_8:2val
      # - B_PATH=/nnUNet//3d-2d2_1000EP_8vs2val
      - A_PATH=/nnUNet/outputs/output_Task510_2d_ATLAS_ATLAS_1000EP_5Fold
      - B_PATH=/nnUNet/ensemble/Ensemble(3d,2d0)_1000EP_5Fold
      - DST_PATH=union/Union(3d,Ensemble(3d,2d0))_1000ep_5Fold
      # - SAVE_ALSO_NPY=false
      # - COPY_PKL=false
    entrypoint: python3 union.py